# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelBezier.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFile.setGeometry(QtCore.QRect(690, 30, 112, 34))
        self.OpenFile.setObjectName("OpenFile")
        self.ImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageLabel.setGeometry(QtCore.QRect(10, 30, 640, 480))
        self.ImageLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.LabelButton = QtWidgets.QPushButton(self.centralwidget)
        self.LabelButton.setEnabled(True)
        self.LabelButton.setGeometry(QtCore.QRect(700, 170, 91, 41))
        self.LabelButton.setObjectName("LabelButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(670, 130, 281, 151))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.OpenFolder = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFolder.setGeometry(QtCore.QRect(820, 30, 112, 34))
        self.OpenFolder.setObjectName("OpenFolder")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(670, 290, 281, 221))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.ControlPointList = QtWidgets.QListWidget(self.groupBox_2)
        self.ControlPointList.setGeometry(QtCore.QRect(10, 30, 261, 161))
        self.ControlPointList.setObjectName("ControlPointList")
        self.LabelDone = QtWidgets.QPushButton(self.centralwidget)
        self.LabelDone.setGeometry(QtCore.QRect(830, 170, 91, 41))
        self.LabelDone.setObjectName("LabelDone")
        self.LabelReset = QtWidgets.QPushButton(self.centralwidget)
        self.LabelReset.setGeometry(QtCore.QRect(700, 220, 91, 41))
        self.LabelReset.setObjectName("LabelReset")
        self.LabelSave = QtWidgets.QPushButton(self.centralwidget)
        self.LabelSave.setGeometry(QtCore.QRect(830, 220, 91, 41))
        self.LabelSave.setObjectName("LabelSave")
        self.OpenNext = QtWidgets.QPushButton(self.centralwidget)
        self.OpenNext.setGeometry(QtCore.QRect(690, 80, 112, 34))
        self.OpenNext.setObjectName("OpenNext")
        self.LabelPrevious = QtWidgets.QPushButton(self.centralwidget)
        self.LabelPrevious.setGeometry(QtCore.QRect(820, 80, 112, 34))
        self.LabelPrevious.setObjectName("LabelPrevious")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.OpenFile.raise_()
        self.ImageLabel.raise_()
        self.LabelButton.raise_()
        self.OpenFolder.raise_()
        self.LabelDone.raise_()
        self.LabelReset.raise_()
        self.LabelSave.raise_()
        self.OpenNext.raise_()
        self.LabelPrevious.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LabelBezier"))
        self.OpenFile.setText(_translate("MainWindow", "Open File"))
        self.LabelButton.setText(_translate("MainWindow", "Start"))
        self.groupBox.setTitle(_translate("MainWindow", "Label Action"))
        self.OpenFolder.setText(_translate("MainWindow", "Open Folder"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control Points"))
        self.LabelDone.setText(_translate("MainWindow", "Done"))
        self.LabelReset.setText(_translate("MainWindow", "Reset"))
        self.LabelSave.setText(_translate("MainWindow", "Save"))
        self.OpenNext.setText(_translate("MainWindow", "Next"))
        self.LabelPrevious.setText(_translate("MainWindow", "Previous"))

